require("dotenv").config();
const mongoose = require("mongoose");
const fs       = require("fs");

const LotteryData      = require("../models/FullLotteryData");
const { detectCycles } = require("./cycleDetector");

// ═══════════════════════════════════════════════════════════════
// PHASE 11 — RAW DAILY SEQUENCE BACKTRACKING
//
// Approach: stop looking at statistics.
// Look at actual daily outputs as a formula problem.
//
// Tests:
//   A. PRIZE-VALUE FORMULA
//      Is prize(N) = f(N) deterministically?
//      Test: range, digit sum, modular, digit product, etc.
//
//   B. DAY-TO-DAY NUMBER RELATIONSHIP
//      Given today's exact draw set, can we derive tomorrow's?
//      Test: complement, shift, XOR, modular transformation.
//
//   C. UNIQUE SEQUENCE FORMULA
//      The 10,000 unique first appearances per cycle —
//      is this sequence generated by a formula?
//      Test: arithmetic progression, skip patterns, etc.
//
//   D. WITHIN-DAY NUMBER RELATIONSHIP
//      On any given day, do the drawn numbers satisfy
//      a common equation? f(n1) = f(n2) = ... = constant?
//
//   E. PRIZE POOL POSITION FORMULA
//      Given number N and its position in the prize pool,
//      is prize deterministic by some rule?
// ═══════════════════════════════════════════════════════════════

async function runPhase11() {
  const dbUri = process.env.MONGODB_URI || "mongodb://localhost:27017/numbergrid";
  await mongoose.connect(dbUri);
  console.log("✅ Connected to MongoDB\n");

  const draws     = await LotteryData.find({}).sort({ drawDate: 1 }).lean();
  const allCycles = detectCycles(draws);

  const validCycles  = allCycles.filter((c) => c.cycleNumber !== 1);
  const trainCycles  = validCycles.filter((c) => c.isComplete);
  const currentCycle = validCycles.find((c) => !c.isComplete);

  console.log("📋 PHASE 11 — RAW DAILY SEQUENCE BACKTRACKING\n");

  // ═══════════════════════════════════════════════════════════════
  // PART A — PRIZE-VALUE FORMULA SEARCH
  // For each number 0000–9999, is prize determined by the number?
  // ═══════════════════════════════════════════════════════════════
  console.log("═".repeat(65));
  console.log("PART A — PRIZE-VALUE FORMULA SEARCH");
  console.log("  Q: Is prize(N) = f(N) for some computable function f?");
  console.log("═".repeat(65));
  testPrizeValueFormula(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART B — DAY-TO-DAY TRANSFORMATION
  // Given set S(day N), can we derive S(day N+1)?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART B — DAY-TO-DAY NUMBER TRANSFORMATION");
  console.log("  Q: S(day N+1) = T(S(day N)) for some transform T?");
  console.log("═".repeat(65));
  testDayToDayTransformation(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART C — UNIQUE SEQUENCE FORMULA
  // List all 10,000 numbers in order of first appearance.
  // Is this sequence generated by a formula?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART C — UNIQUE SEQUENCE FORMULA SEARCH");
  console.log("  Q: Is the first-appearance order generated by a rule?");
  console.log("═".repeat(65));
  testUniqueSequenceFormula(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART D — WITHIN-DAY COMMON PROPERTY
  // On each day, do ALL drawn numbers share a common property?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART D — WITHIN-DAY COMMON PROPERTY SEARCH");
  console.log("  Q: Do all numbers drawn on day N share f(N) = constant?");
  console.log("═".repeat(65));
  testWithinDayCommonProperty(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART E — PRIZE ASSIGNMENT RULES
  // Comprehensive: for each prize tier, what rule selects numbers?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART E — PRIZE ASSIGNMENT RULE SEARCH");
  console.log("  Q: Is there a computable rule that determines prize tier?");
  console.log("═".repeat(65));
  testPrizeAssignmentRules(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART F — PRIZE NUMBER POSITIONAL ANALYSIS
  // For each prize tier: which POSITIONS in 0000–9999 win it?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART F — PRIZE NUMBER POSITIONAL ANALYSIS");
  console.log("  Q: Do prize tiers concentrate in specific numeric ranges?");
  console.log("═".repeat(65));
  testPrizePositionalAnalysis(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART G — NUMBER COMPLEMENT ANALYSIS
  // N and (9999-N) — do they win the same prize? Appear same day?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART G — NUMBER COMPLEMENT ANALYSIS");
  console.log("  Q: N and (9999-N): same prize? Same day? Pattern?");
  console.log("═".repeat(65));
  testComplementAnalysis(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART H — SORTED DAILY SEQUENCE: ARITHMETIC GAPS
  // Sort each day's draw. Look at differences between consecutive.
  // Are gaps arithmetic? Fibonacci? Power-based?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART H — SORTED DAILY SEQUENCE: ARITHMETIC GAP ANALYSIS");
  console.log("  Q: Do sorted drawn numbers form an arithmetic sequence?");
  console.log("═".repeat(65));
  testArithmeticGaps(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART I — CROSS-CYCLE NUMBER RANK FORMULA
  // Rank each number by first appearance in cycle 2.
  // Does rank in cycle 2 predict rank in cycle 3, 4?
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART I — CROSS-CYCLE RANK FORMULA");
  console.log("  Q: rank_C3(N) = f(rank_C2(N)) for some formula f?");
  console.log("═".repeat(65));
  testCrossCycleRankFormula(trainCycles);

  // ═══════════════════════════════════════════════════════════════
  // PART J — ACTUAL DAILY DATA DUMP
  // Print first 5 days of cycle 4 raw data for manual inspection
  // ═══════════════════════════════════════════════════════════════
  console.log("\n" + "═".repeat(65));
  console.log("PART J — RAW DAILY DATA (cycle 4, first 7 days)");
  console.log("  For manual pattern inspection");
  console.log("═".repeat(65));
  printRawDailyData(trainCycles);

  await mongoose.disconnect();
}

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────
const numVal   = (s) => parseInt(s, 10);
const digitSum = (s) => s.split("").reduce((a,d) => a+Number(d), 0);
const digitProd= (s) => s.split("").reduce((a,d) => a*(Number(d)||1), 1);
const mean     = (arr) => arr.length ? arr.reduce((a,b)=>a+b,0)/arr.length : 0;
const stdDev   = (arr) => {
  if (arr.length<2) return 0;
  const m = mean(arr);
  return Math.sqrt(arr.reduce((s,v)=>s+(v-m)**2,0)/arr.length);
};

// Build number → prizes map across all training cycles
function buildPrizeMap(trainCycles) {
  const map = new Map(); // number → [prizes across cycles]
  for (const cycle of trainCycles) {
    for (const dayEntry of cycle.drawEntries) {
      for (const { number, prize, isNew } of dayEntry.numbers) {
        if (!isNew) continue;
        if (!map.has(number)) map.set(number, []);
        map.get(number).push(prize);
      }
    }
  }
  return map;
}

// Build cycle → [ {day, number, prize} ] sorted by day
function buildCycleSequence(cycle) {
  const seq = [];
  for (const dayEntry of cycle.drawEntries) {
    for (const { number, prize, isNew } of dayEntry.numbers) {
      if (!isNew) continue;
      seq.push({ day: dayEntry.dayIndexInCycle, number, prize, val: numVal(number) });
    }
  }
  return seq.sort((a,b) => a.day - b.day || a.val - b.val);
}

// ═══════════════════════════════════════════════════════════════
// PART A — PRIZE-VALUE FORMULA SEARCH
// ═══════════════════════════════════════════════════════════════
function testPrizeValueFormula(trainCycles) {
  const prizeMap = buildPrizeMap(trainCycles);
  const prizes   = [5000, 2000, 1000, 500, 200, 100, 50];

  // For each number, get its modal prize
  const numPrize = new Map();
  for (const [num, prizeArr] of prizeMap) {
    const freq = {};
    prizeArr.forEach((p) => { freq[p] = (freq[p]||0)+1; });
    const top = Object.entries(freq).sort((a,b)=>b[1]-a[1])[0];
    numPrize.set(num, Number(top[0]));
  }

  console.log(`\n  Testing prize(N) = f(N) hypotheses:\n`);

  // ── Hypothesis 1: Number range → prize
  console.log(`  H1: Number range determines prize`);
  const rangeBuckets = {};
  for (const [num, prize] of numPrize) {
    const bucket = Math.floor(numVal(num) / 1000) * 1000;
    if (!rangeBuckets[bucket]) rangeBuckets[bucket] = {};
    rangeBuckets[bucket][prize] = (rangeBuckets[bucket][prize]||0)+1;
  }
  let rangeSignal = false;
  for (const [bucket, dist] of Object.entries(rangeBuckets)) {
    const total = Object.values(dist).reduce((a,b)=>a+b,0);
    const topPrize = Object.entries(dist).sort((a,b)=>b[1]-a[1])[0];
    const pct = (topPrize[1]/total*100).toFixed(1);
    if (parseFloat(pct) > 80) rangeSignal = true;
    console.log(`    Range ${String(bucket).padEnd(5)}-${Number(bucket)+999}: dominant prize ₹${topPrize[0]} (${pct}%)`);
  }
  console.log(`    → ${rangeSignal ? "✅ SIGNAL: range predicts prize!" : "❌ No range-prize formula"}`);

  // ── Hypothesis 2: Digit sum → prize
  console.log(`\n  H2: Digit sum → prize`);
  const dsumPrize = {};
  for (const [num, prize] of numPrize) {
    const ds = digitSum(num);
    if (!dsumPrize[ds]) dsumPrize[ds] = {};
    dsumPrize[ds][prize] = (dsumPrize[ds][prize]||0)+1;
  }
  let dsumSignal = false;
  const dsumResults = [];
  for (let ds = 0; ds <= 36; ds++) {
    if (!dsumPrize[ds]) continue;
    const total = Object.values(dsumPrize[ds]).reduce((a,b)=>a+b,0);
    const topPrize = Object.entries(dsumPrize[ds]).sort((a,b)=>b[1]-a[1])[0];
    const pct = (topPrize[1]/total*100).toFixed(1);
    dsumResults.push({ ds, topPrize: topPrize[0], pct, total });
    if (parseFloat(pct) > 75 && total > 20) dsumSignal = true;
  }
  // Print interesting ones (not just ₹100 dominant)
  const interestingDs = dsumResults.filter((r) => r.topPrize !== "100" || parseFloat(r.pct) > 80);
  interestingDs.forEach((r) => {
    console.log(`    digitSum=${String(r.ds).padEnd(3)}: dominant ₹${r.topPrize} (${r.pct}%, n=${r.total})`);
  });
  console.log(`    → ${dsumSignal ? "✅ SIGNAL: digit sum predicts prize!" : "❌ No digit-sum formula"}`);

  // ── Hypothesis 3: Number mod K → prize
  console.log(`\n  H3: Number mod K → prize (testing K=2 to 100)`);
  let bestModResult = { K: 0, accuracy: 0, prizeK: 0 };
  for (const K of [2,3,4,5,6,7,8,9,10,11,12,13,17,19,23,37,50,100]) {
    const modPrize = {};
    for (const [num, prize] of numPrize) {
      const mod = numVal(num) % K;
      if (!modPrize[mod]) modPrize[mod] = {};
      modPrize[mod][prize] = (modPrize[mod][prize]||0)+1;
    }
    // For each residue, what % have same prize?
    let totalCorrect=0, totalAll=0;
    for (const [mod, dist] of Object.entries(modPrize)) {
      const total = Object.values(dist).reduce((a,b)=>a+b,0);
      const top   = Math.max(...Object.values(dist));
      totalCorrect += top;
      totalAll     += total;
    }
    const accuracy = totalAll > 0 ? totalCorrect/totalAll*100 : 0;
    if (accuracy > bestModResult.accuracy) {
      bestModResult = { K, accuracy: parseFloat(accuracy.toFixed(2)) };
    }
  }
  console.log(`    Best K: ${bestModResult.K} → accuracy ${bestModResult.accuracy}%`);
  console.log(`    Random baseline (always guess ₹100): ~${
    (() => {
      let c=0; for (const [,p] of numPrize) if (p===100) c++;
      return (c/numPrize.size*100).toFixed(1);
    })()
  }%`);
  console.log(`    → ${bestModResult.accuracy > 75 ? "✅ SIGNAL!" : "❌ No modular formula"}`);

  // ── Hypothesis 4: Last digit → prize
  console.log(`\n  H4: Last digit → prize`);
  const lastDigitPrize = {};
  for (const [num, prize] of numPrize) {
    const ld = num[3]; // last digit
    if (!lastDigitPrize[ld]) lastDigitPrize[ld] = {};
    lastDigitPrize[ld][prize] = (lastDigitPrize[ld][prize]||0)+1;
  }
  for (let d=0; d<=9; d++) {
    const dist  = lastDigitPrize[String(d)] || {};
    const total = Object.values(dist).reduce((a,b)=>a+b,0);
    if (!total) continue;
    const top   = Object.entries(dist).sort((a,b)=>b[1]-a[1])[0];
    const pct   = (top[1]/total*100).toFixed(1);
    console.log(`    Last digit ${d}: dominant ₹${top[0]} (${pct}%)`);
  }

  // ── Hypothesis 5: First digit → prize
  console.log(`\n  H5: First digit → prize`);
  const firstDigitPrize = {};
  for (const [num, prize] of numPrize) {
    const fd = num[0];
    if (!firstDigitPrize[fd]) firstDigitPrize[fd] = {};
    firstDigitPrize[fd][prize] = (firstDigitPrize[fd][prize]||0)+1;
  }
  for (let d=0; d<=9; d++) {
    const dist  = firstDigitPrize[String(d)] || {};
    const total = Object.values(dist).reduce((a,b)=>a+b,0);
    if (!total) continue;
    const top   = Object.entries(dist).sort((a,b)=>b[1]-a[1])[0];
    const pct   = (top[1]/total*100).toFixed(1);
    const breakdown = prizes.map((p) => `₹${p}:${((dist[p]||0)/total*100).toFixed(1)}%`).join(" ");
    console.log(`    First digit ${d}: ${breakdown}`);
  }

  // ── Hypothesis 6: Specific 2-digit combinations
  console.log(`\n  H6: High-prize numbers — any common pattern?`);
  const highPrizeNums = [...numPrize.entries()].filter(([,p]) => p >= 2000);
  console.log(`    Numbers with predicted prize ≥₹2000: ${highPrizeNums.length}`);

  // Check digit properties of high-prize numbers
  const hpDigitSums  = highPrizeNums.map(([n]) => digitSum(n));
  const hpFirstDigits = highPrizeNums.map(([n]) => Number(n[0]));
  const hpLastDigits  = highPrizeNums.map(([n]) => Number(n[3]));
  const hpMods        = [7,11,13,17].map((K) => ({
    K, dist: highPrizeNums.reduce((acc,[n]) => {
      const mod = numVal(n) % K;
      acc[mod] = (acc[mod]||0)+1;
      return acc;
    }, {})
  }));

  console.log(`    Digit sum: mean=${mean(hpDigitSums).toFixed(2)} std=${stdDev(hpDigitSums).toFixed(2)}`);
  console.log(`    First digit distribution: ${[...new Array(10).keys()].map((d)=>
    `${d}:${hpFirstDigits.filter((x)=>x===d).length}`).join(" ")}`);

  // Find if any mod K concentrates high-prize numbers
  for (const { K, dist } of hpMods) {
    const maxMod = Object.entries(dist).sort((a,b)=>b[1]-a[1])[0];
    const expected = highPrizeNums.length / K;
    const elevation = maxMod[1] / expected;
    if (elevation > 1.5) {
      console.log(`    ✅ mod ${K}: residue ${maxMod[0]} has ${maxMod[1]} high-prize numbers (${elevation.toFixed(2)}x expected)`);
    }
  }

  // ── Hypothesis 7: Palindromes, repeated digits
  console.log(`\n  H7: Special number patterns → prize`);
  const palindromes = [...numPrize.entries()].filter(([n]) => n === n.split("").reverse().join(""));
  const repeating   = [...numPrize.entries()].filter(([n]) => new Set(n.split("")).size === 1);
  const sequential  = [...numPrize.entries()].filter(([n]) => {
    const d = n.split("").map(Number);
    return d.every((v,i) => i===0 || v===d[i-1]+1);
  });

  const palPrizes = palindromes.map(([,p])=>p);
  const repPrizes = repeating.map(([,p])=>p);

  console.log(`    Palindromes (${palindromes.length}): avg prize ₹${mean(palPrizes).toFixed(0)}, samples: ${palindromes.slice(0,5).map(([n,p])=>`${n}→₹${p}`).join(" ")}`);
  console.log(`    All-same digits (${repeating.length}): ${repeating.map(([n,p])=>`${n}→₹${p}`).join(" ")}`);
  console.log(`    Sequential (${sequential.length}): ${sequential.slice(0,5).map(([n,p])=>`${n}→₹${p}`).join(" ")}`);
}

// ═══════════════════════════════════════════════════════════════
// PART B — DAY-TO-DAY TRANSFORMATION
// ═══════════════════════════════════════════════════════════════
function testDayToDayTransformation(trainCycles) {
  const cycle = trainCycles.find((c) => c.cycleNumber === 2);
  if (!cycle) return;

  const entries = cycle.drawEntries.slice(0, 20);

  // For each consecutive pair of days, check various transforms
  console.log(`\n  Testing transforms between consecutive days (cycle 2):\n`);

  let bestTransform = { name: "none", matchRate: 0 };

  for (let i = 0; i < Math.min(entries.length-1, 10); i++) {
    const todayNums = new Set(entries[i].numbers.filter((n)=>n.isNew).map((n)=>n.number));
    const tomorNums = new Set(entries[i+1].numbers.filter((n)=>n.isNew).map((n)=>n.number));

    if (todayNums.size === 0 || tomorNums.size === 0) continue;

    // Transform 1: N+K (shift by constant)
    for (const K of [1, 10, 100, 1000, 33, 37]) {
      const shifted = new Set([...todayNums].map((n) => String((numVal(n)+K) % 10000).padStart(4,"0")));
      const overlap = [...shifted].filter((n) => tomorNums.has(n)).length;
      const rate    = overlap / tomorNums.size;
      if (rate > 0.1) {
        console.log(`    Day ${i+1}→${i+2}: shift+${K} matches ${overlap}/${tomorNums.size} (${(rate*100).toFixed(1)}%)`);
        if (rate > bestTransform.matchRate) bestTransform = { name: `shift+${K}`, matchRate: rate };
      }
    }

    // Transform 2: Complement (9999-N)
    const compl = new Set([...todayNums].map((n) => String(9999-numVal(n)).padStart(4,"0")));
    const complOverlap = [...compl].filter((n) => tomorNums.has(n)).length;
    if (complOverlap > 5) {
      console.log(`    Day ${i+1}→${i+2}: complement matches ${complOverlap}/${tomorNums.size} (${(complOverlap/tomorNums.size*100).toFixed(1)}%)`);
    }

    // Transform 3: 10000-N
    const inv = new Set([...todayNums].map((n) => String((10000-numVal(n))%10000).padStart(4,"0")));
    const invOverlap = [...inv].filter((n) => tomorNums.has(n)).length;
    if (invOverlap > 5) {
      console.log(`    Day ${i+1}→${i+2}: inverse(10000-N) matches ${invOverlap}/${tomorNums.size}`);
    }

    // Transform 4: digit reversal
    const rev = new Set([...todayNums].map((n) => n.split("").reverse().join("")));
    const revOverlap = [...rev].filter((n) => tomorNums.has(n)).length;
    if (revOverlap > 5) {
      console.log(`    Day ${i+1}→${i+2}: digit-reverse matches ${revOverlap}/${tomorNums.size}`);
    }

    // Transform 5: rotate digits
    const rot1 = new Set([...todayNums].map((n) => n[1]+n[2]+n[3]+n[0]));
    const rot1Overlap = [...rot1].filter((n) => tomorNums.has(n)).length;
    if (rot1Overlap > 5) {
      console.log(`    Day ${i+1}→${i+2}: rotate-left matches ${rot1Overlap}/${tomorNums.size}`);
    }

    // Raw overlap (same numbers appear tomorrow)
    const rawOverlap = [...todayNums].filter((n) => tomorNums.has(n)).length;
    const expectedOverlap = (todayNums.size * tomorNums.size) / 10000;
    if (rawOverlap > expectedOverlap * 1.5) {
      console.log(`    Day ${i+1}→${i+2}: RAW overlap=${rawOverlap} vs expected=${expectedOverlap.toFixed(1)} (${(rawOverlap/expectedOverlap).toFixed(2)}x)`);
    }
  }

  // Overall same-number consecutive day overlap
  let totalOverlap=0, totalExpected=0, totalDays=0;
  for (const cycle of trainCycles) {
    for (let i=0; i<cycle.drawEntries.length-1; i++) {
      const a = new Set(cycle.drawEntries[i].numbers.filter((n)=>n.isNew).map((n)=>n.number));
      const b = new Set(cycle.drawEntries[i+1].numbers.filter((n)=>n.isNew).map((n)=>n.number));
      if (a.size<5 || b.size<5) continue;
      const ov = [...a].filter((n)=>b.has(n)).length;
      totalOverlap += ov;
      totalExpected += (a.size*b.size)/10000;
      totalDays++;
    }
  }
  const overlapRatio = totalOverlap/totalExpected;
  console.log(`\n  Overall consecutive-day overlap ratio: ${overlapRatio.toFixed(3)}x expected`);
  console.log(`  (1.0=random, >2.0=structural)  → ${overlapRatio > 1.3 ? "✅ SIGNAL" : "❌ random"}`);
  console.log(`  Best transform found: ${bestTransform.name} (${(bestTransform.matchRate*100).toFixed(1)}%)`);
}

// ═══════════════════════════════════════════════════════════════
// PART C — UNIQUE SEQUENCE FORMULA
// ═══════════════════════════════════════════════════════════════
function testUniqueSequenceFormula(trainCycles) {
  for (const cycle of trainCycles.slice(0,2)) {
    const seq = buildCycleSequence(cycle);
    const vals = seq.map((s) => s.val);

    console.log(`\n  Cycle ${cycle.cycleNumber} unique sequence (${vals.length} numbers):`);
    console.log(`  First 30: ${vals.slice(0,30).join(" ")}`);

    // ── Test: is it an arithmetic progression with some gaps?
    const diffs = vals.slice(1).map((v,i) => v - vals[i]);
    const avgDiff = mean(diffs);
    const stdDiff = stdDev(diffs);
    console.log(`  Avg diff between consecutive: ${avgDiff.toFixed(2)}, std: ${stdDiff.toFixed(2)}`);

    // ── Test: does it follow N*K mod 10000 pattern?
    // i.e. is vals[i] ≡ vals[0] + i*step (mod 10000)?
    let bestLCG = { step: 0, matches: 0 };
    for (const step of [1, 3, 7, 11, 13, 17, 19, 23, 37, 97, 101, 137, 997, 1001, 1337, 3333]) {
      let matches = 0;
      for (let i=0; i<Math.min(vals.length, 100); i++) {
        const predicted = (vals[0] + i*step) % 10000;
        if (Math.abs(vals[i] - predicted) < 50) matches++;
      }
      if (matches > bestLCG.matches) bestLCG = { step, matches };
    }
    console.log(`  Best arithmetic step: ${bestLCG.step} (${bestLCG.matches}/100 within ±50)`);

    // ── Test: LCG (Linear Congruential Generator)
    // x[n+1] = (a*x[n] + c) mod 10000
    console.log(`  Testing LCG: x[n+1] = (a*x[n] + c) mod 10000...`);
    let bestLCGFull = { a:0, c:0, matches:0 };
    const sampleVals = vals.slice(0, 50);
    for (const a of [3, 7, 11, 13, 17, 19, 21, 23, 37, 41, 43, 47]) {
      for (const c of [0, 1, 3, 7, 11, 100, 1000, 3141]) {
        let matches = 0;
        let x = sampleVals[0];
        for (let i=1; i<sampleVals.length; i++) {
          x = (a*x + c) % 10000;
          if (Math.abs(x - sampleVals[i]) < 100) matches++;
        }
        if (matches > bestLCGFull.matches) bestLCGFull = { a, c, matches };
      }
    }
    console.log(`  Best LCG: a=${bestLCGFull.a}, c=${bestLCGFull.c} → ${bestLCGFull.matches}/49 within ±100`);
    if (bestLCGFull.matches > 20) {
      console.log(`  ✅ STRONG LCG SIGNAL — this may be the generation formula!`);
    }

    // ── Test: sorted within each day — do they form a progression?
    const dayEntries = cycle.drawEntries.slice(0,5);
    console.log(`\n  First 5 days sorted new numbers:`);
    for (const dayEntry of dayEntries) {
      const newNums = dayEntry.numbers
        .filter((n)=>n.isNew)
        .map((n)=>numVal(n.number))
        .sort((a,b)=>a-b);
      if (newNums.length === 0) continue;
      const diffs2 = newNums.slice(1).map((v,i) => v-newNums[i]);
      const uniqueDiffs = [...new Set(diffs2)].sort((a,b)=>a-b);
      console.log(`    Day ${dayEntry.dayIndexInCycle} (${newNums.length} new): first 10: ${newNums.slice(0,10).join(" ")}`);
      console.log(`    Gaps: min=${Math.min(...diffs2)} max=${Math.max(...diffs2)} avg=${mean(diffs2).toFixed(1)}`);
      console.log(`    Most common gaps: ${uniqueDiffs.slice(0,5).join(" ")}`);
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// PART D — WITHIN-DAY COMMON PROPERTY
// ═══════════════════════════════════════════════════════════════
function testWithinDayCommonProperty(trainCycles) {
  const tests = [];

  for (const cycle of trainCycles) {
    for (const dayEntry of cycle.drawEntries.slice(0,50)) {
      const newNums = dayEntry.numbers
        .filter((n)=>n.isNew)
        .map((n)=>n.number);
      if (newNums.length < 10) continue;

      // Test: all have same digit sum mod K?
      for (const K of [2,3,4,5,6,7,8,9,10]) {
        const mods = new Set(newNums.map((n) => digitSum(n) % K));
        if (mods.size === 1) {
          tests.push({ type:`digitSum%${K}`, value:[...mods][0], cycle:cycle.cycleNumber, day:dayEntry.dayIndexInCycle, n:newNums.length });
        }
      }

      // Test: all have same value mod K?
      for (const K of [2,3,4,5,7,10,11,13]) {
        const mods = new Set(newNums.map((n) => numVal(n) % K));
        if (mods.size === 1) {
          tests.push({ type:`val%${K}`, value:[...mods][0], cycle:cycle.cycleNumber, day:dayEntry.dayIndexInCycle, n:newNums.length });
        }
      }

      // Test: all first digits same?
      const firstDigits = new Set(newNums.map((n)=>n[0]));
      if (firstDigits.size === 1) {
        tests.push({ type:"firstDigit", value:[...firstDigits][0], cycle:cycle.cycleNumber, day:dayEntry.dayIndexInCycle, n:newNums.length });
      }

      // Test: all last digits same?
      const lastDigits = new Set(newNums.map((n)=>n[3]));
      if (lastDigits.size === 1) {
        tests.push({ type:"lastDigit", value:[...lastDigits][0], cycle:cycle.cycleNumber, day:dayEntry.dayIndexInCycle, n:newNums.length });
      }
    }
  }

  if (tests.length === 0) {
    console.log(`\n  No days found where ALL new numbers share a common property.`);
    console.log(`  → No within-day formula exists.`);
  } else {
    console.log(`\n  Found ${tests.length} cases where all new numbers share a property:`);
    tests.slice(0,20).forEach((t) => {
      console.log(`    Cycle ${t.cycle} Day ${t.day}: all ${t.n} new nums have ${t.type}=${t.value}`);
    });
  }

  // Weaker test: what % of each day shares a common property?
  console.log(`\n  Partial property sharing (what % of day's new numbers share same digitSum%K):`);
  const shareRates = {};
  for (const K of [3,7,10]) {
    let totalShare=0, totalDays=0;
    for (const cycle of trainCycles) {
      for (const dayEntry of cycle.drawEntries) {
        const newNums = dayEntry.numbers.filter((n)=>n.isNew).map((n)=>n.number);
        if (newNums.length < 5) continue;
        const modCounts = {};
        newNums.forEach((n) => { const m=digitSum(n)%K; modCounts[m]=(modCounts[m]||0)+1; });
        const maxShare = Math.max(...Object.values(modCounts));
        totalShare += maxShare/newNums.length;
        totalDays++;
      }
    }
    const avgShare = totalShare/totalDays;
    shareRates[K] = avgShare;
    const expectedRandom = 1/K;
    console.log(`    digitSum%${K}: avg max share = ${(avgShare*100).toFixed(1)}% (random expected: ${(expectedRandom*100).toFixed(1)}%)`);
  }
}

// ═══════════════════════════════════════════════════════════════
// PART E — PRIZE ASSIGNMENT RULES
// ═══════════════════════════════════════════════════════════════
function testPrizeAssignmentRules(trainCycles) {
  const prizeMap = buildPrizeMap(trainCycles);

  // Build the complete prize assignment table
  const numPrizeFull = new Map(); // number → { prize: count }
  for (const [num, prizeArr] of prizeMap) {
    const freq = {};
    prizeArr.forEach((p) => { freq[p]=(freq[p]||0)+1; });
    numPrizeFull.set(num, freq);
  }

  // Test: for each prize tier, what is the NUMBER DENSITY in each 500-unit range?
  console.log(`\n  Prize density by 500-unit range:`);
  const rangeSize = 500;
  const ranges    = Array.from({length:20}, (_,i)=>i*rangeSize);
  const prizes    = [5000, 2000, 1000, 500, 200, 100];

  console.log(`  Range     | ${prizes.map((p)=>`₹${p}%  `).join(" | ")}`);
  console.log(`  ` + "-".repeat(75));

  let anyConcentrated = false;
  for (const rangeStart of ranges) {
    const inRange = [...numPrizeFull.entries()]
      .filter(([n]) => numVal(n)>=rangeStart && numVal(n)<rangeStart+rangeSize);
    if (inRange.length===0) continue;

    const prizeTotals = {};
    inRange.forEach(([,freq]) => {
      Object.entries(freq).forEach(([p,c]) => { prizeTotals[p]=(prizeTotals[p]||0)+c; });
    });
    const grandTotal = Object.values(prizeTotals).reduce((a,b)=>a+b,0);

    const cols = prizes.map((p) => {
      const pct = grandTotal>0 ? ((prizeTotals[p]||0)/grandTotal*100) : 0;
      return String(pct.toFixed(1)+"%").padEnd(7);
    });

    // Check if any prize is >2x its overall rate
    const overallRates = { 5000:6.7, 2000:2.4, 1000:9.1, 500:28.9, 200:2.6, 100:46.7 };
    prizes.forEach((p) => {
      const pct = grandTotal>0 ? ((prizeTotals[p]||0)/grandTotal*100) : 0;
      if (pct > (overallRates[p]||0)*2 && grandTotal>50) anyConcentrated=true;
    });

    console.log(`  ${String(`${rangeStart}-${rangeStart+rangeSize-1}`).padEnd(10)} | ${cols.join(" | ")}`);
  }
  console.log(`\n  Prize concentration signal: ${anyConcentrated ? "✅ YES — certain ranges have elevated prize rates!" : "❌ No range concentration"}`);

  // Special: find ALL numbers that ALWAYS win ₹5000
  const always5000 = [...numPrizeFull.entries()]
    .filter(([,freq]) => Object.keys(freq).length===1 && freq[5000]>=2);
  console.log(`\n  Numbers that ALWAYS win ₹5000 (in all cycles): ${always5000.length}`);
  if (always5000.length > 0) {
    const nums = always5000.map(([n])=>n).sort();
    console.log(`  Numbers: ${nums.join(" ")}`);
    // Find pattern in these numbers
    const vals5000 = nums.map((n)=>numVal(n));
    const ds5000   = nums.map((n)=>digitSum(n));
    const mod7     = nums.map((n)=>numVal(n)%7);
    const mod11    = nums.map((n)=>numVal(n)%11);
    console.log(`  Digit sums: ${ds5000.join(" ")}`);
    console.log(`  Values mod 7:  ${[...new Set(mod7)].sort((a,b)=>a-b).join(" ")}`);
    console.log(`  Values mod 11: ${[...new Set(mod11)].sort((a,b)=>a-b).join(" ")}`);
    console.log(`  First digits:  ${[...new Set(nums.map((n)=>n[0]))].sort().join(" ")}`);
    console.log(`  Last digits:   ${[...new Set(nums.map((n)=>n[3]))].sort().join(" ")}`);
  }
}

// ═══════════════════════════════════════════════════════════════
// PART F — PRIZE POSITIONAL ANALYSIS
// ═══════════════════════════════════════════════════════════════
function testPrizePositionalAnalysis(trainCycles) {
  const prizeMap = buildPrizeMap(trainCycles);

  // For each prize, get the numeric values and find distribution stats
  const byPrize = { 5000:[], 2000:[], 1000:[], 500:[], 200:[], 100:[], 50:[] };

  for (const [num, prizeArr] of prizeMap) {
    // Use first-appearance prize (most reliable)
    const freq  = {};
    prizeArr.forEach((p) => { freq[p]=(freq[p]||0)+1; });
    const top   = Object.entries(freq).sort((a,b)=>b[1]-a[1])[0];
    const prize = Number(top[0]);
    const v     = numVal(num);
    if (byPrize[prize]) byPrize[prize].push(v);
  }

  console.log(`\n  Numeric value distribution per prize tier:`);
  console.log(`  Prize  | Count | Mean   | Std    | Min  | Max  | Spread uniform?`);
  console.log(`  ` + "-".repeat(75));

  for (const prize of [5000, 2000, 1000, 500, 200, 100, 50]) {
    const vals = byPrize[prize];
    if (!vals.length) continue;
    const m    = mean(vals);
    const s    = stdDev(vals);
    const mn   = Math.min(...vals);
    const mx   = Math.max(...vals);
    // Expected std if uniform: ~2887 (std of uniform 0-9999)
    const isUniform = s > 2500 && s < 3200;
    console.log(
      `  ₹${String(prize).padEnd(5)} | ${String(vals.length).padEnd(5)} | ` +
      `${String(Math.round(m)).padEnd(6)} | ${String(Math.round(s)).padEnd(6)} | ` +
      `${String(mn).padEnd(4)} | ${String(mx).padEnd(4)} | ${isUniform ? "✅ yes" : "❌ CONCENTRATED"}`
    );
  }
}

// ═══════════════════════════════════════════════════════════════
// PART G — COMPLEMENT ANALYSIS (N and 9999-N)
// ═══════════════════════════════════════════════════════════════
function testComplementAnalysis(trainCycles) {
  const prizeMap = buildPrizeMap(trainCycles);

  // For each number N, compare with 9999-N
  let samePrize=0, sameDayCount=0, totalPairs=0;
  const samePrizeExamples = [];

  for (const cycle of trainCycles) {
    // Build number → firstDay map
    const firstDayMap = new Map();
    for (const dayEntry of cycle.drawEntries) {
      for (const { number, isNew } of dayEntry.numbers) {
        if (isNew && !firstDayMap.has(number)) {
          firstDayMap.set(number, dayEntry.dayIndexInCycle);
        }
      }
    }

    // Check pairs
    for (const [num, firstDay] of firstDayMap) {
      const v     = numVal(num);
      if (v > 4999) continue; // only check lower half to avoid double-counting
      const comp  = String(9999-v).padStart(4,"0");
      const compDay = firstDayMap.get(comp);
      if (!compDay) continue;

      totalPairs++;

      // Same first day?
      if (firstDay === compDay) sameDayCount++;

      // Same prize?
      const numPrize  = prizeMap.get(num);
      const compPrize = prizeMap.get(comp);
      if (numPrize && compPrize) {
        const np = numPrize[0];
        const cp = compPrize[0];
        if (np === cp) {
          samePrize++;
          if (samePrizeExamples.length < 10) {
            samePrizeExamples.push({ num, comp, prize: np });
          }
        }
      }
    }
  }

  const sameDayRate  = totalPairs>0 ? (sameDayCount/totalPairs*100).toFixed(2) : 0;
  const samePrizeRate= totalPairs>0 ? (samePrize/totalPairs*100).toFixed(2) : 0;
  const expectedSameDay = (1/350*100).toFixed(2); // ~1/cycleLen

  console.log(`\n  Complement analysis (N and 9999-N):`);
  console.log(`  Total pairs checked: ${totalPairs.toLocaleString()}`);
  console.log(`  Same first-day rate: ${sameDayRate}% (expected ~${expectedSameDay}%)`);
  console.log(`  Same prize rate: ${samePrizeRate}%`);
  console.log(`  Same-prize examples: ${samePrizeExamples.map((e)=>`${e.num}+${e.comp}=₹${e.prize}`).join(", ")}`);
  console.log(`  → ${parseFloat(sameDayRate) > parseFloat(expectedSameDay)*2 ? "✅ SIGNAL: complements appear same day!" : "❌ random"}`);

  // Also test N + (5000-N) mod 10000
  console.log(`\n  Testing N and (5000-N)%10000 pairing...`);
}

// ═══════════════════════════════════════════════════════════════
// PART H — ARITHMETIC GAPS
// ═══════════════════════════════════════════════════════════════
function testArithmeticGaps(trainCycles) {
  // For each day, sort new numbers and look for arithmetic patterns
  const cycle = trainCycles.find((c) => c.cycleNumber === 4);
  if (!cycle) return;

  let totalArithDays=0, totalDays=0;

  for (const dayEntry of cycle.drawEntries.slice(0,30)) {
    const newNums = dayEntry.numbers
      .filter((n)=>n.isNew)
      .map((n)=>numVal(n.number))
      .sort((a,b)=>a-b);

    if (newNums.length < 10) continue;
    totalDays++;

    const diffs = newNums.slice(1).map((v,i) => v-newNums[i]);
    const uniqueDiffs = [...new Set(diffs)];

    // Is it arithmetic? (all same diff)
    if (uniqueDiffs.length === 1) {
      totalArithDays++;
      console.log(`  Day ${dayEntry.dayIndexInCycle}: ARITHMETIC sequence! step=${uniqueDiffs[0]}, n=${newNums.length}`);
      continue;
    }

    // Top 3 most common gaps
    const gapFreq = {};
    diffs.forEach((d) => { gapFreq[d]=(gapFreq[d]||0)+1; });
    const topGaps = Object.entries(gapFreq).sort((a,b)=>b[1]-a[1]).slice(0,3);
    const topGapCount = topGaps.reduce((a,[,v])=>a+v,0);
    const topGapPct   = (topGapCount/diffs.length*100).toFixed(0);

    // Is there a dominant gap?
    if (parseFloat(topGaps[0]?.[1]||0)/diffs.length > 0.5) {
      console.log(`  Day ${dayEntry.dayIndexInCycle}: dominant gap=${topGaps[0][0]} (${(topGaps[0][1]/diffs.length*100).toFixed(0)}%), n=${newNums.length}`);
    }
  }

  if (totalArithDays === 0) {
    console.log(`\n  No arithmetic sequences found in daily draws.`);
    console.log(`  → Numbers are not drawn in arithmetic progressions.`);
  } else {
    console.log(`\n  Arithmetic days: ${totalArithDays}/${totalDays}`);
  }
}

// ═══════════════════════════════════════════════════════════════
// PART I — CROSS-CYCLE RANK FORMULA
// ═══════════════════════════════════════════════════════════════
function testCrossCycleRankFormula(trainCycles) {
  const c2 = trainCycles.find((c) => c.cycleNumber === 2);
  const c3 = trainCycles.find((c) => c.cycleNumber === 3);
  const c4 = trainCycles.find((c) => c.cycleNumber === 4);
  if (!c2||!c3||!c4) return;

  // Build rank maps (rank = position in unique sequence 1..10000)
  const buildRankMap = (cycle) => {
    const seq = buildCycleSequence(cycle);
    const map = new Map();
    seq.forEach((entry, i) => map.set(entry.number, i+1));
    return map;
  };

  const rank2 = buildRankMap(c2);
  const rank3 = buildRankMap(c3);
  const rank4 = buildRankMap(c4);

  // Get all numbers present in all 3 cycles
  const common = [...rank2.keys()].filter((n) => rank3.has(n) && rank4.has(n));

  console.log(`\n  Cross-cycle rank analysis (${common.length} numbers):`);

  // Test: rank3 = f(rank2)?
  // Simple: rank3 = 10001 - rank2 (reverse ordering)
  let reverseMatches = 0;
  const TOL = 500; // tolerance in rank units

  for (const num of common.slice(0, 1000)) {
    const r2 = rank2.get(num);
    const r3 = rank3.get(num);
    const predictedR3 = 10001 - r2;
    if (Math.abs(predictedR3 - r3) < TOL) reverseMatches++;
  }
  console.log(`  Reverse formula (rank3 = 10001-rank2): ${reverseMatches}/1000 within ±${TOL}`);

  // Test: rank4 = f(rank3)?
  let reverseMatches2 = 0;
  for (const num of common.slice(0, 1000)) {
    const r3 = rank3.get(num);
    const r4 = rank4.get(num);
    const predictedR4 = 10001 - r3;
    if (Math.abs(predictedR4 - r4) < TOL) reverseMatches2++;
  }
  console.log(`  Reverse formula (rank4 = 10001-rank3): ${reverseMatches2}/1000 within ±${TOL}`);

  // Test: shift formula
  for (const shift of [0, 1000, 2000, 3000, 5000]) {
    let matches = 0;
    for (const num of common.slice(0, 200)) {
      const r2 = rank2.get(num);
      const r4 = rank4.get(num);
      if (Math.abs(((r2+shift-1)%10000)+1 - r4) < TOL) matches++;
    }
    if (matches > 20) console.log(`  Shift formula (rank4=(rank2+${shift})%10000): ${matches}/200`);
  }

  // Show actual rank comparison for first 20 numbers
  console.log(`\n  First 20 numbers by C2 rank:`);
  console.log(`  Number | Rank_C2 | Rank_C3 | Rank_C4 | C3-C2 | C4-C3`);
  console.log(`  ` + "-".repeat(58));
  const first20 = [...rank2.entries()].sort((a,b)=>a[1]-b[1]).slice(0,20);
  first20.forEach(([num, r2]) => {
    const r3 = rank3.get(num) ?? "?";
    const r4 = rank4.get(num) ?? "?";
    const d32 = typeof r3==="number" ? r3-r2 : "?";
    const d43 = typeof r4==="number" && typeof r3==="number" ? r4-r3 : "?";
    console.log(
      `  ${num}   | ${String(r2).padEnd(7)} | ${String(r3).padEnd(7)} | ` +
      `${String(r4).padEnd(7)} | ${String(d32).padEnd(5)} | ${d43}`
    );
  });
}

// ═══════════════════════════════════════════════════════════════
// PART J — RAW DAILY DATA DUMP
// ═══════════════════════════════════════════════════════════════
function printRawDailyData(trainCycles) {
  const cycle = trainCycles.find((c) => c.cycleNumber === 4);
  if (!cycle) return;

  console.log(`\n  Cycle 4 — First 7 draw days (new numbers only, sorted):`);

  for (const dayEntry of cycle.drawEntries.slice(0,7)) {
    const byPrize = {};
    dayEntry.numbers.filter((n)=>n.isNew).forEach((n) => {
      if (!byPrize[n.prize]) byPrize[n.prize] = [];
      byPrize[n.prize].push(numVal(n.number));
    });
    Object.values(byPrize).forEach((arr) => arr.sort((a,b)=>a-b));

    console.log(`\n  Day ${dayEntry.dayIndexInCycle} (${new Date(dayEntry.drawDate).toISOString().split("T")[0]}):`);
    for (const prize of [5000, 2000, 1000, 500, 200, 100, 50]) {
      const nums = byPrize[prize];
      if (!nums || !nums.length) continue;
      console.log(`    ₹${String(prize).padEnd(5)}: ${nums.join(" ")}`);
    }

    // All new numbers sorted
    const all = dayEntry.numbers.filter((n)=>n.isNew).map((n)=>numVal(n.number)).sort((a,b)=>a-b);
    console.log(`    ALL (${all.length}): ${all.slice(0,30).join(" ")} ${all.length>30?"...":""}`);
    const diffs = all.slice(1).map((v,i)=>v-all[i]);
    console.log(`    Gaps: min=${Math.min(...diffs)} max=${Math.max(...diffs)} avg=${mean(diffs).toFixed(1)}`);
  }
}

// ─────────────────────────────────────────────────────────────
runPhase11().catch((err) => {
  console.error("❌ Phase 11 failed:", err);
  process.exit(1);
});